from datetime import datetime
from app.domain.entities import Notification
from app.domain.repositories import NotificationRepository
from app.presentation.schemas import NotificationCreate
from sqlalchemy.orm import Session

class CreateNotificationUseCase:
    def __init__(self, repository: NotificationRepository):
        self.repository = repository

    def execute(self, notification_create: NotificationCreate, db: Session) -> Notification:
        notification = Notification(
            id=None,  # ID will be generated by the database
            user_id=notification_create.user_id,
            message=notification_create.message,
            read_status=False,
            created_at=datetime.utcnow()
        )
        return self.repository.create_notification(notification, db)